project_name: traggo
builds:
  - id: linux-amd64
    main: ./
    goos: [linux]
    goarch: ['amd64']
    flags: ['-tags="netgo osusergo sqlite_omit_load_extension"']
    ldflags: ["-s","-w","-linkmode","external","-extldflags","-static","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
checksum:
  disable: true
changelog:
  skip: true
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/jo-m/traggo-server:amd64-latest"
      - "ghcr.io/jo-m/traggo-server:amd64-{{ .FullCommit }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/jo-m/traggo-server"
